version: '2'
services:
  postfix:
    image: ghcr.io/puijken/docker-postfix:latest
    expose:
    - "25"
    env_file:
      - .env
    restart: always
    volumes:
     - "/etc/localtime:/etc/localtime:ro"
